use_frameworks!

pod 'Alamofire'
pod 'ObjectMapper'
pod 'PromiseKit/Alamofire', '~> 6.0'
pod 'PromiseKit', '~> 6.0'

target 'KENetworking_Example' do
  pod 'KENetworking', :path => '../'

  target 'KENetworking_Tests' do
    inherit! :search_paths

    
  end
end
